# named list of all robots
robots:
  # cf231:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E7E7
  #   initial_position: [0, 0, 0]
  #   type: cf21  # see robot_types
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    # firmware_logging:
    #   enabled: true
    #   custom_topics:
    #     topic_name3: 
    #       frequency: 1
    #       vars: ["acc.x", "acc.y"]
  cf1:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E701
    initial_position: [-0.5, -0.5, 0]
    # initial_position: [0.0, 0.0, 0]
    type: cf21  # see robot_types
    ip_add: "192.168.4.1"
    port: 5000
  cf2:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E702
    initial_position: [-0.5, 0.0, 0]
    # initial_position: [0.0, 0.0, 0]
    type: cf21  # see robot_types
    ip_add: "192.168.4.1"
    port: 5000
  cf3:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E703
    initial_position: [-0.5, 0.5, 0]
    # initial_position: [0.0, 0.0, 0]
    type: cf21  # see robot_types
    ip_add: "192.168.4.1"
    port: 5000
  # cf4:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E704
  #   initial_position: [0.0, -0.5, 0]
  #   # initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf5:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E705
  #   initial_position: [0.0, 0.0, 0]
  #   # initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf6:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E706
  #   # initial_position: [0.0, 0.5, 0]
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf7:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E707
  #   # initial_position: [0.5, -0.5, 0]
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf8:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E708
  #   # initial_position: [0.5, 0.0, 0]
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  
  # cf9:
  #   enabled: true
  #   uri: radio://1/100/2M/E7E7E7E709
  #   # initial_position: [0.5, 0.5, 0]
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  
  # cf10:
  #   enabled: true
  #   uri: radio://1/100/2M/E7E7E7E710
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf11:
  #   enabled: true
  #   uri: radio://1/100/2M/E7E7E7E711
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf12:
  #   enabled: true
  #   uri: radio://1/100/2M/E7E7E7E712
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf13:
  #   enabled: true
  #   uri: radio://1/100/2M/E7E7E7E713
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf14:
  #   enabled: true
  #   uri: radio://1/100/2M/E7E7E7E714
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf15:
  #   enabled: true
  #   uri: radio://1/100/2M/E7E7E7E715
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf16:
  #   enabled: true
  #   uri: radio://1/100/2M/E7E7E7E716
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types

  # cf17:
  #   enabled: true
  #   uri: radio://2/120/2M/E7E7E7E717
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf18:
  #   enabled: true
  #   uri: radio://2/120/2M/E7E7E7E718
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf19:
  #   enabled: true
  #   uri: radio://2/120/2M/E7E7E7E719
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf20:
  #   enabled: true
  #   uri: radio://2/120/2M/E7E7E7E720
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf21:
  #   enabled: true
  #   uri: radio://2/120/2M/E7E7E7E721
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf22:
  #   enabled: true
  #   uri: radio://2/120/2M/E7E7E7E722
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf23:
  #   enabled: true
  #   uri: radio://2/120/2M/E7E7E7E723
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf24:
  #   enabled: true
  #   uri: radio://2/120/2M/E7E7E7E724
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
  # cf25:
  #   enabled: true
  #   uri: radio://2/120/2M/E7E7E7E725
  #   initial_position: [0.0, 0.0, 0]
  #   type: cf21  # see robot_types
    # firmware_logging:
    #   enabled: true
    #   default_topics:
    #     pose:
    #       frequency: 1 # Hz

    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    #firmware_logging:
    #  custom_topics:
    #    topic_name3: 
    #      frequency: 1
    #      vars: ["acc.x", "acc.y", "acc.z"]
# Definition of the various robot types
robot_types:
  cf21:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: default_single_marker
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    # firmware_logging:
    #   enabled: true
    #   default_topics:
    #     pose:
    #       frequency: 1 # Hz
    #   custom_topics:
    #    topic_name3: 
    #      frequency: 1
    #      vars: ["acc.x", "acc.y", "acc.z"]

  cf21_mocap_deck:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: mocap_deck
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5

# global settings for all robots
all:
  # firmware logging for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_logging:
    enabled: true
    default_topics:
     # remove to disable default topic
      pose:
        frequency: 5 # Hz
    # custom_topics:
    #  topic_name1:
    #    frequency: 10 # Hz
    #    vars: ["stateEstimateZ.x", "stateEstimateZ.y", "stateEstimateZ.z", "pm.vbat"]
    #  topic_name2:
    #    frequency: 1 # Hz
    #    vars: ["stabilizer.roll", "stabilizer.pitch", "stabilizer.yaw"]
  # firmware parameters for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 1 # 1: PID, 2: mellinger
    # ring:
    #   effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
    #   solidBlue: 255 # if set to solid color
    #   solidGreen: 0 # if set to solid color
    #   solidRed: 0 # if set to solid color
    #   headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    # kalman:
    #   resetEstimation: 1
      # robustTdoa: 1
      # pNAcc_xy: 0.5
      # pNVel: 0.5
      # mNGyro_rollpitch: 0.05
      # mNGyro_yaw: 0.05
    motion:
      adaptive: 1
      flowStdFixed: 2.0
  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats
